services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=PerHueDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345@abc!
    ports:
      - "54320:5432"  # ánh xạ port 54320 của host tới 5432 trong container PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: PerHue.Api/Dockerfile
    container_name: perhue-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=PerHueDb;Username=postgres;Password=12345@abc!;Pooling=true;

volumes:
  pgdata: