// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerHue.Infrastructure.Persistence;

#nullable disable

namespace PerHue.Infrastructure.Migrations
{
    [DbContext(typeof(PerHueDbContext))]
    [Migration("20251113160829_dbV2")]
    partial class dbV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapsulePaletteColor", b =>
                {
                    b.Property<int>("CapsulePaletteId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.HasKey("CapsulePaletteId", "ColorId")
                        .HasName("PK__CapsuleP__797C104513E70E3C");

                    b.HasIndex("ColorId");

                    b.ToTable("CapsulePalette_Color", (string)null);
                });

            modelBuilder.Entity("ColorTestResult", b =>
                {
                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("ColorId", "TestResultId")
                        .HasName("PK__Color_Te__E383041598B1D152");

                    b.HasIndex("TestResultId");

                    b.ToTable("Color_TestResult", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.AiPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AiPictur__3214EC07AE7B38FA");

                    b.HasIndex("TestRequestId");

                    b.ToTable("AiPicture", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.AiTestResult", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AvoidedColor")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ColorTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedColor")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__AiTestRe__3214EC071B4BE6DB");

                    b.HasIndex("ColorTypeId");

                    b.ToTable("AiTestResult", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.CapsulePalette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CapsuleP__3214EC075C14A32F");

                    b.HasIndex("ColorTypeId");

                    b.ToTable("CapsulePalette", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Color__3214EC07E36B66DC");

                    b.HasIndex(new[] { "Name" }, "UQ__Color__737584F6909CB759")
                        .IsUnique();

                    b.HasIndex(new[] { "HexCode" }, "UQ__Color__A7CAA840740075F6")
                        .IsUnique();

                    b.ToTable("Color", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ColorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__ColorTyp__3214EC071EC0A38D");

                    b.ToTable("ColorType", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FacebookAccount")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InstagramAccount")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LinkedInAccount")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short>("YearsOfExperience")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__Expert__3214EC07F1596FE6");

                    b.ToTable("Expert", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ExpertTestRequest", b =>
                {
                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ExpertId", "TestRequestId")
                        .HasName("PK__Expert_T__0B386C703BAF4E1B");

                    b.HasIndex("TestRequestId");

                    b.ToTable("Expert_TestRequest", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Receiver")
                        .HasColumnType("int");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC0706E4EFA3");

                    b.HasIndex("Receiver");

                    b.HasIndex("TestRequestId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3214EC07075A3817");

                    b.HasIndex("UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.PaymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Mesage")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Metadata")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PaymentL__3214EC07F48B03B3");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentLog", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Source")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Picture__3214EC076080BF44");

                    b.HasIndex("TestRequestId");

                    b.ToTable("Picture", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC0753600E4A");

                    b.HasIndex("UserAccountId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC074010C1AB");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ServicePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short>("Duration")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<short>("Uses")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__ServiceP__3214EC078C39A6F6");

                    b.ToTable("ServicePackage", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EyesColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HairColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LipsColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SkinColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TypeOfTest")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TestRequ__3214EC075F8180AD");

                    b.HasIndex("UserAccountId");

                    b.ToTable("TestRequest", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestColor")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ColorTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TestRequestId")
                        .HasColumnType("int");

                    b.Property<string>("WorstColor")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__TestResp__3214EC07F693B863");

                    b.HasIndex("ColorTypeId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("TestRequestId");

                    b.ToTable("TestResponse", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Picture")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TestResu__3214EC07E1E743F4");

                    b.HasIndex("UserId");

                    b.ToTable("TestResult", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAitested")
                        .HasColumnType("bit")
                        .HasColumnName("IsAITested");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProfilePicture")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__UserAcco__3214EC076ED9788D");

                    b.HasIndex("RoleId");

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<short>("RemainingUses")
                        .HasColumnType("smallint");

                    b.Property<int>("ServicePackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserSubs__3214EC07C52CFB30");

                    b.HasIndex("ServicePackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscription", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.VerifyInformation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdentityPhoto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Languages")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short>("YearsOfExperience")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__VerifyIn__3214EC07659C21D7");

                    b.ToTable("VerifyInformation", (string)null);
                });

            modelBuilder.Entity("CapsulePaletteColor", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.CapsulePalette", null)
                        .WithMany()
                        .HasForeignKey("CapsulePaletteId")
                        .IsRequired()
                        .HasConstraintName("FKCapsulePal722223");

                    b.HasOne("PerHue.Domain.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FKCapsulePal75933");
                });

            modelBuilder.Entity("ColorTestResult", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FKColor_Test74218");

                    b.HasOne("PerHue.Domain.Entities.TestResult", null)
                        .WithMany()
                        .HasForeignKey("TestResultId")
                        .IsRequired()
                        .HasConstraintName("FKColor_Test80884");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.AiPicture", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.TestRequest", "TestRequest")
                        .WithMany("AiPictures")
                        .HasForeignKey("TestRequestId")
                        .IsRequired()
                        .HasConstraintName("FKAiPicture425173");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.AiTestResult", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ColorType", "ColorType")
                        .WithMany("AiTestResults")
                        .HasForeignKey("ColorTypeId")
                        .IsRequired()
                        .HasConstraintName("FKAiTestResu112231");

                    b.HasOne("PerHue.Domain.Entities.TestRequest", "IdNavigation")
                        .WithOne("AiTestResult")
                        .HasForeignKey("PerHue.Domain.Entities.AiTestResult", "Id")
                        .IsRequired()
                        .HasConstraintName("FKAiTestResu885671");

                    b.Navigation("ColorType");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.CapsulePalette", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ColorType", "ColorType")
                        .WithMany("CapsulePalettes")
                        .HasForeignKey("ColorTypeId")
                        .IsRequired()
                        .HasConstraintName("FKCapsulePal268315");

                    b.Navigation("ColorType");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Expert", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "IdNavigation")
                        .WithOne("Expert")
                        .HasForeignKey("PerHue.Domain.Entities.Expert", "Id")
                        .IsRequired()
                        .HasConstraintName("FKExpert610142");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ExpertTestRequest", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Expert", "Expert")
                        .WithMany("ExpertTestRequests")
                        .HasForeignKey("ExpertId")
                        .IsRequired()
                        .HasConstraintName("FKExpert_Tes360727");

                    b.HasOne("PerHue.Domain.Entities.TestRequest", "TestRequest")
                        .WithMany("ExpertTestRequests")
                        .HasForeignKey("TestRequestId")
                        .IsRequired()
                        .HasConstraintName("FKExpert_Tes912400");

                    b.Navigation("Expert");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Notification", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "ReceiverNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("Receiver")
                        .IsRequired()
                        .HasConstraintName("FKNotificati163299");

                    b.HasOne("PerHue.Domain.Entities.TestRequest", "TestRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("TestRequestId")
                        .IsRequired()
                        .HasConstraintName("FKNotificati150945");

                    b.Navigation("ReceiverNavigation");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Payment", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserSubscription", "IdNavigation")
                        .WithOne("Payment")
                        .HasForeignKey("PerHue.Domain.Entities.Payment", "Id")
                        .IsRequired()
                        .HasConstraintName("FKPayment451401");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKPayment506916");

                    b.Navigation("IdNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.PaymentLog", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Payment", "Payment")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("PaymentId")
                        .IsRequired()
                        .HasConstraintName("FKPaymentLog793082");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Picture", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.TestRequest", "TestRequest")
                        .WithMany("Pictures")
                        .HasForeignKey("TestRequestId")
                        .IsRequired()
                        .HasConstraintName("FKPicture509691");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserAccountId")
                        .IsRequired()
                        .HasConstraintName("FKRefreshTok433736");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestRequest", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("TestRequests")
                        .HasForeignKey("UserAccountId")
                        .IsRequired()
                        .HasConstraintName("FKTestReques386664");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestResponse", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ColorType", "ColorType")
                        .WithMany("TestResponses")
                        .HasForeignKey("ColorTypeId")
                        .IsRequired()
                        .HasConstraintName("FKTestRespon437540");

                    b.HasOne("PerHue.Domain.Entities.Expert", "Expert")
                        .WithMany("TestResponses")
                        .HasForeignKey("ExpertId")
                        .IsRequired()
                        .HasConstraintName("FKTestRespon382802");

                    b.HasOne("PerHue.Domain.Entities.TestRequest", "TestRequest")
                        .WithMany("TestResponses")
                        .HasForeignKey("TestRequestId")
                        .IsRequired()
                        .HasConstraintName("FKTestRespon934475");

                    b.Navigation("ColorType");

                    b.Navigation("Expert");

                    b.Navigation("TestRequest");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKTestResult297045");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Role", "Role")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FKUserAccoun312334");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ServicePackage", "ServicePackage")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("ServicePackageId")
                        .IsRequired()
                        .HasConstraintName("FKUserSubscr443828");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKUserSubscr62907");

                    b.Navigation("ServicePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.VerifyInformation", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "IdNavigation")
                        .WithOne("VerifyInformation")
                        .HasForeignKey("PerHue.Domain.Entities.VerifyInformation", "Id")
                        .IsRequired()
                        .HasConstraintName("FKVerifyInfo301359");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ColorType", b =>
                {
                    b.Navigation("AiTestResults");

                    b.Navigation("CapsulePalettes");

                    b.Navigation("TestResponses");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Expert", b =>
                {
                    b.Navigation("ExpertTestRequests");

                    b.Navigation("TestResponses");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Payment", b =>
                {
                    b.Navigation("PaymentLogs");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ServicePackage", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestRequest", b =>
                {
                    b.Navigation("AiPictures");

                    b.Navigation("AiTestResult");

                    b.Navigation("ExpertTestRequests");

                    b.Navigation("Notifications");

                    b.Navigation("Pictures");

                    b.Navigation("TestResponses");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("Expert");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TestRequests");

                    b.Navigation("TestResults");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("VerifyInformation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserSubscription", b =>
                {
                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
