// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerHue.Infrastructure.Persistence;

#nullable disable

namespace PerHue.Infrastructure.Migrations
{
    [DbContext(typeof(PerHueDbContext))]
    [Migration("20250920161411_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapsulePaletteColor", b =>
                {
                    b.Property<int>("CapsulePaletteId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.HasKey("CapsulePaletteId", "ColorId")
                        .HasName("PK__CapsuleP__797C10454EFFDC8E");

                    b.HasIndex("ColorId");

                    b.ToTable("CapsulePalette_Color", (string)null);
                });

            modelBuilder.Entity("ColorTestResult", b =>
                {
                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("ColorId", "TestResultId")
                        .HasName("PK__Color_Te__E3830415516B0AF4");

                    b.HasIndex("TestResultId");

                    b.ToTable("Color_TestResult", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Slogan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Brand__3214EC07C94BDFA0");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.CapsulePalette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CapsuleP__3214EC076251D5B8");

                    b.HasIndex("ColorTypeId");

                    b.ToTable("CapsulePalette", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Carousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Picture")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Carousel__3214EC07C0B4D60E");

                    b.HasIndex("BrandId");

                    b.ToTable("Carousel", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC07E95320B5");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Person1")
                        .HasColumnType("int");

                    b.Property<int>("Person2")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ChatRoom__3214EC07109FD287");

                    b.HasIndex("Person1");

                    b.HasIndex("Person2");

                    b.ToTable("ChatRoom", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Color__3214EC072E6AAEA1");

                    b.HasIndex(new[] { "Name" }, "UQ__Color__737584F69EE4A9BF")
                        .IsUnique();

                    b.HasIndex(new[] { "HexCode" }, "UQ__Color__A7CAA840B41ADCCC")
                        .IsUnique();

                    b.ToTable("Color", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ColorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__ColorTyp__3214EC0720EADA05");

                    b.ToTable("ColorType", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FacebookAccount")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("InstagramAccount")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LinkedInAccount")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short>("YearsOfExperience")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__Expert__3214EC076CA50B66");

                    b.ToTable("Expert", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TestResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Message__3214EC07B0CF5A22");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("Sender");

                    b.HasIndex("TestResultId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Read");

                    b.Property<int>("Receiver")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07A7C0006D");

                    b.HasIndex("Receiver");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3214EC07FCC5BA56");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.PaymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Mesage")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Metadata")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PaymentL__3214EC07C4F0B962");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentLog", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reaction")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Post__3214EC07C0550A83");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sale")
                        .HasColumnType("decimal(1, 1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Product__3214EC071DE2B3D5");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ProductPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Picture")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProductP__3214EC0779401686");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPicture", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC076296A932");

                    b.HasIndex("UserAccountId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Reaction")
                        .HasColumnType("int");

                    b.Property<int>("ReplyId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reply__3214EC0730AE6FBC");

                    b.HasIndex("PostId");

                    b.HasIndex("ReplyId");

                    b.ToTable("Reply", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReplyId")
                        .HasColumnType("int");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Report__3214EC07819B64A3");

                    b.HasIndex("ReplyId");

                    b.HasIndex("ReportTypeId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ReportTy__3214EC07C727F08C");

                    b.ToTable("ReportType", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC0775E85296");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ServicePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short?>("Duration")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ServiceP__3214EC074CAFF8F5");

                    b.ToTable("ServicePackage", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.SimpleColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hexcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SimpleCo__3214EC0792E547B5");

                    b.HasIndex("TestResultId");

                    b.ToTable("SimpleColor", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EyesColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HairColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LipsColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SkinColor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TestResu__3214EC078C548135");

                    b.HasIndex("ColorTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("TestResult", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Topic__3214EC07D06F4F9C");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAitested")
                        .HasColumnType("bit")
                        .HasColumnName("IsAITested");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProfilePicture")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__UserAcco__3214EC075BFD24F7");

                    b.HasIndex("RoleId");

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<short?>("Duration")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ServicePackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserSubs__3214EC07D15E2842");

                    b.HasIndex("ServicePackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscription", (string)null);
                });

            modelBuilder.Entity("PerHue.Domain.Entities.VerifyInformation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Languages")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<short>("YearsOfExperience")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK__VerifyIn__3214EC07236A998D");

                    b.ToTable("VerifyInformation", (string)null);
                });

            modelBuilder.Entity("TestResultCapsulePalette", b =>
                {
                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.Property<int>("CapsulePaletteId")
                        .HasColumnType("int");

                    b.HasKey("TestResultId", "CapsulePaletteId")
                        .HasName("PK__TestResu__E95C53E446D81DAD");

                    b.HasIndex("CapsulePaletteId");

                    b.ToTable("TestResult_CapsulePalette", (string)null);
                });

            modelBuilder.Entity("CapsulePaletteColor", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.CapsulePalette", null)
                        .WithMany()
                        .HasForeignKey("CapsulePaletteId")
                        .IsRequired()
                        .HasConstraintName("FKCapsulePal722223");

                    b.HasOne("PerHue.Domain.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FKCapsulePal75933");
                });

            modelBuilder.Entity("ColorTestResult", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FKColor_Test74218");

                    b.HasOne("PerHue.Domain.Entities.TestResult", null)
                        .WithMany()
                        .HasForeignKey("TestResultId")
                        .IsRequired()
                        .HasConstraintName("FKColor_Test80884");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Brand", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "IdNavigation")
                        .WithOne("Brand")
                        .HasForeignKey("PerHue.Domain.Entities.Brand", "Id")
                        .IsRequired()
                        .HasConstraintName("FKBrand133468");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.CapsulePalette", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ColorType", "ColorType")
                        .WithMany("CapsulePalettes")
                        .HasForeignKey("ColorTypeId")
                        .IsRequired()
                        .HasConstraintName("FKCapsulePal268315");

                    b.Navigation("ColorType");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Carousel", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Brand", "Brand")
                        .WithMany("Carousels")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FKCarousel383250");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ChatRoom", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "Person1Navigation")
                        .WithMany("ChatRoomPerson1Navigations")
                        .HasForeignKey("Person1")
                        .IsRequired()
                        .HasConstraintName("FKChatRoom84230");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "Person2Navigation")
                        .WithMany("ChatRoomPerson2Navigations")
                        .HasForeignKey("Person2")
                        .IsRequired()
                        .HasConstraintName("FKChatRoom84229");

                    b.Navigation("Person1Navigation");

                    b.Navigation("Person2Navigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Expert", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "IdNavigation")
                        .WithOne("Expert")
                        .HasForeignKey("PerHue.Domain.Entities.Expert", "Id")
                        .IsRequired()
                        .HasConstraintName("FKExpert610142");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Message", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .IsRequired()
                        .HasConstraintName("FKMessage32066");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "SenderNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("Sender")
                        .IsRequired()
                        .HasConstraintName("FKMessage169107");

                    b.HasOne("PerHue.Domain.Entities.TestResult", "TestResult")
                        .WithMany("Messages")
                        .HasForeignKey("TestResultId")
                        .HasConstraintName("FKMessage712793");

                    b.Navigation("ChatRoom");

                    b.Navigation("SenderNavigation");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Notification", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "ReceiverNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("Receiver")
                        .IsRequired()
                        .HasConstraintName("FKNotificati163299");

                    b.Navigation("ReceiverNavigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Payment", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKPayment506916");

                    b.HasOne("PerHue.Domain.Entities.UserSubscription", "UserSubscription")
                        .WithMany("Payments")
                        .HasForeignKey("UserSubscriptionId")
                        .IsRequired()
                        .HasConstraintName("FKPayment766453");

                    b.Navigation("User");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.PaymentLog", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Payment", "Payment")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("PaymentId")
                        .IsRequired()
                        .HasConstraintName("FKPaymentLog793082");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Post", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Topic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FKPost883700");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKPost986101");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Product", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FKProduct960477");

                    b.HasOne("PerHue.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FKProduct365970");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ProductPicture", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Product", "Product")
                        .WithMany("ProductPictures")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FKProductPic772500");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserAccountId")
                        .IsRequired()
                        .HasConstraintName("FKRefreshTok433736");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Reply", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Post", "Post")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FKReply241689");

                    b.HasOne("PerHue.Domain.Entities.Reply", "ReplyNavigation")
                        .WithMany("InverseReplyNavigation")
                        .HasForeignKey("ReplyId")
                        .IsRequired()
                        .HasConstraintName("FKReply96398");

                    b.Navigation("Post");

                    b.Navigation("ReplyNavigation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Report", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Reply", "Reply")
                        .WithMany("Reports")
                        .HasForeignKey("ReplyId")
                        .HasConstraintName("FKReport370169");

                    b.HasOne("PerHue.Domain.Entities.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .IsRequired()
                        .HasConstraintName("FKReport882469");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("Reports")
                        .HasForeignKey("UserAccountId")
                        .IsRequired()
                        .HasConstraintName("FKReport36488");

                    b.Navigation("Reply");

                    b.Navigation("ReportType");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.SimpleColor", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.TestResult", "TestResult")
                        .WithMany("SimpleColors")
                        .HasForeignKey("TestResultId")
                        .IsRequired()
                        .HasConstraintName("FKSimpleColo694170");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ColorType", "ColorType")
                        .WithMany("TestResults")
                        .HasForeignKey("ColorTypeId")
                        .IsRequired()
                        .HasConstraintName("FKTestResult1660");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKTestResult297045");

                    b.Navigation("ColorType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.Role", "Role")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FKUserAccoun312334");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.ServicePackage", "ServicePackage")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("ServicePackageId")
                        .IsRequired()
                        .HasConstraintName("FKUserSubscr443828");

                    b.HasOne("PerHue.Domain.Entities.UserAccount", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKUserSubscr62907");

                    b.Navigation("ServicePackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.VerifyInformation", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.UserAccount", "IdNavigation")
                        .WithOne("VerifyInformation")
                        .HasForeignKey("PerHue.Domain.Entities.VerifyInformation", "Id")
                        .IsRequired()
                        .HasConstraintName("FKVerifyInfo301359");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("TestResultCapsulePalette", b =>
                {
                    b.HasOne("PerHue.Domain.Entities.CapsulePalette", null)
                        .WithMany()
                        .HasForeignKey("CapsulePaletteId")
                        .IsRequired()
                        .HasConstraintName("FKTestResult47353");

                    b.HasOne("PerHue.Domain.Entities.TestResult", null)
                        .WithMany()
                        .HasForeignKey("TestResultId")
                        .IsRequired()
                        .HasConstraintName("FKTestResult848745");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Carousels");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ColorType", b =>
                {
                    b.Navigation("CapsulePalettes");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Payment", b =>
                {
                    b.Navigation("PaymentLogs");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Post", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductPictures");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Reply", b =>
                {
                    b.Navigation("InverseReplyNavigation");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.ServicePackage", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.TestResult", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("SimpleColors");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("Brand");

                    b.Navigation("ChatRoomPerson1Navigations");

                    b.Navigation("ChatRoomPerson2Navigations");

                    b.Navigation("Expert");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Posts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("TestResults");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("VerifyInformation");
                });

            modelBuilder.Entity("PerHue.Domain.Entities.UserSubscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
